

import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nxtxlie
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    double num,ans;
    int calculation; 
    DefaultListModel<String> listModel;
    
    
    public NewJFrame() {
        initComponents();
        
        listModel = new DefaultListModel<>();
        
        
       int i =0;
       do{
        onButton.setEnabled(false);   //on button disable
        i++;
       }while(i<10);
        

    
    }
    
    
    
    public void arithmetic()
    {
        switch(calculation)
        {
            case 1: //addition
                    ans = num + Double.parseDouble(display.getText());
                    display.setText(Double.toString(ans));
                    listModel.addElement(Double.toString(ans)); //stores answer to list
                     history.setModel(listModel);
                    break;
                    
            case 2: //subtraction
                    ans = num - Double.parseDouble(display.getText());
                    display.setText(Double.toString(ans));
                    listModel.addElement(Double.toString(ans));//stores answer to list
                    history.setModel(listModel);
                    break;        
            case 3: //multipulcation 
                    ans = num * Double.parseDouble(display.getText());
                    display.setText(Double.toString(ans));
                    listModel.addElement(Double.toString(ans));//stores answer to list
                     history.setModel(listModel);
                    break;
                    
            case 4: //division
                    ans = num / Double.parseDouble(display.getText());
                    display.setText(Double.toString(ans));
                    listModel.addElement(Double.toString(ans));//stores answer to list
                    history.setModel(listModel);
                    break;
                    
        }
        
        
    }
    
    
    
    
    // creating a method to turn on all buttons
    
    public void enable()
    {
        display.setEnabled(true);
        onButton.setEnabled(true);
        numOne.setEnabled(true);
        numTwo.setEnabled(true);
        numThree.setEnabled(true);
        numFour.setEnabled(true);
        numFive.setEnabled(true);
        numSix.setEnabled(true);
        numSeven.setEnabled(true);
        numEight.setEnabled(true);
        numNine.setEnabled(true);
        numZero.setEnabled(true);
        backButton.setEnabled(true);
        clearButton.setEnabled(true);
        plusButton.setEnabled(true);
        minusButton.setEnabled(true);
        multButton.setEnabled(true);
        divButton.setEnabled(true);
        equalButton.setEnabled(true);
        decimalButton.setEnabled(true);
        history.setEnabled(true);

    }
    
//creating a method to disable all buttons 
    public void disable()
    {
        display.setEnabled(false);
        
        onButton.setEnabled(true);
        numOne.setEnabled(false);
        numTwo.setEnabled(false);
        numThree.setEnabled(false);
        numFour.setEnabled(false);
        numFive.setEnabled(false);
        numSix.setEnabled(false);
        numSeven.setEnabled(false);
        numEight.setEnabled(false);
        numNine.setEnabled(false);
        numZero.setEnabled(false);
        backButton.setEnabled(false);
        clearButton.setEnabled(false);
        plusButton.setEnabled(false);
        minusButton.setEnabled(false);
        multButton.setEnabled(false);
        divButton.setEnabled(false);
        equalButton.setEnabled(false);
        decimalButton.setEnabled(false);
        history.setEnabled(false);
        
    }        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        display = new javax.swing.JTextField();
        onButton = new javax.swing.JRadioButton();
        offButton = new javax.swing.JRadioButton();
        backButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        numOne = new javax.swing.JButton();
        numTwo = new javax.swing.JButton();
        numThree = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        numFour = new javax.swing.JButton();
        numFive = new javax.swing.JButton();
        numSix = new javax.swing.JButton();
        multButton = new javax.swing.JButton();
        numEight = new javax.swing.JButton();
        numSeven = new javax.swing.JButton();
        divButton = new javax.swing.JButton();
        numNine = new javax.swing.JButton();
        decimalButton = new javax.swing.JButton();
        numZero = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        history = new javax.swing.JList<>();
        label = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        display.setEditable(false);
        display.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonGroup1.add(onButton);
        onButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        onButton.setText("ON");
        onButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(offButton);
        offButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        offButton.setText("OFF");
        offButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        backButton.setText("<--");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        clearButton.setText("C");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        plusButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        plusButton.setText("+");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        numOne.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        numOne.setText("1");
        numOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOneActionPerformed(evt);
            }
        });

        numTwo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        numTwo.setText("2");
        numTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTwoActionPerformed(evt);
            }
        });

        numThree.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        numThree.setText("3");
        numThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numThreeActionPerformed(evt);
            }
        });

        minusButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        minusButton.setText("-");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        numFour.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        numFour.setText("4");
        numFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numFourActionPerformed(evt);
            }
        });

        numFive.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        numFive.setText("5");
        numFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numFiveActionPerformed(evt);
            }
        });

        numSix.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        numSix.setText("6");
        numSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSixActionPerformed(evt);
            }
        });

        multButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        multButton.setText("*");
        multButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multButtonActionPerformed(evt);
            }
        });

        numEight.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        numEight.setText("8");
        numEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numEightActionPerformed(evt);
            }
        });

        numSeven.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        numSeven.setText("7");
        numSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSevenActionPerformed(evt);
            }
        });

        divButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        divButton.setText("/");
        divButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divButtonActionPerformed(evt);
            }
        });

        numNine.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        numNine.setText("9");
        numNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numNineActionPerformed(evt);
            }
        });

        decimalButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        decimalButton.setText(".");
        decimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalButtonActionPerformed(evt);
            }
        });

        numZero.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        numZero.setText("0");
        numZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numZeroActionPerformed(evt);
            }
        });

        equalButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        equalButton.setText("=");
        equalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalButtonActionPerformed(evt);
            }
        });

        history.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jScrollPane2.setViewportView(history);

        label.setForeground(new java.awt.Color(255, 0, 0));
        label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(offButton)
                                    .addComponent(onButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numOne, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numThree, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numFour, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numFive, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numSix, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numEight, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numNine, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numZero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(onButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(offButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numOne, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numThree, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numFour, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numFive, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numSix, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numEight, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numNine, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numZero, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    //giving each button it's commands
    
    private void onButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onButtonActionPerformed
        enable();  //call enable method 
    }//GEN-LAST:event_onButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        num = Double.parseDouble(display.getText()); 
        calculation = 1; 
        display.setText("");
        label.setText(num + "+");
    }//GEN-LAST:event_plusButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
      
        //give action to the back button to delete one character everytime it's clicked
        
        int length = display.getText().length();
        int number = display.getText().length() - 1;
        String store;
        
        
        if (length > 0)
        {
            StringBuilder back = new StringBuilder(display.getText());
            back.deleteCharAt(number);
            store = back.toString();
            display.setText(store);
            
            
            
        }
        
        
        
        
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        display.setText(""); //displays nothing once c is clicked
    }//GEN-LAST:event_clearButtonActionPerformed

    private void numTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTwoActionPerformed
        display.setText(display.getText() + "2"); //displays number 2
    }//GEN-LAST:event_numTwoActionPerformed

    private void numFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numFiveActionPerformed
       display.setText(display.getText() + "5"); //displays number 5
    }//GEN-LAST:event_numFiveActionPerformed

    private void numSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSevenActionPerformed
       display.setText(display.getText() + "7"); //displays number 7
    }//GEN-LAST:event_numSevenActionPerformed

    private void multButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multButtonActionPerformed
       
        //call switch statement to multiply
        num = Double.parseDouble(display.getText());
        calculation = 3;
        display.setText("");
        label.setText(num + "*");
    }//GEN-LAST:event_multButtonActionPerformed

    private void numOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOneActionPerformed
        display.setText(display.getText() + "1"); //displays number 1
    }//GEN-LAST:event_numOneActionPerformed

    private void numThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numThreeActionPerformed
        display.setText(display.getText() + "3"); //displays number 3
    }//GEN-LAST:event_numThreeActionPerformed

    private void numFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numFourActionPerformed
        display.setText(display.getText() + "4"); //displays number 4
    }//GEN-LAST:event_numFourActionPerformed

    private void numSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSixActionPerformed
        display.setText(display.getText() + "6"); //displays number 6
    }//GEN-LAST:event_numSixActionPerformed

    private void numEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numEightActionPerformed
        display.setText(display.getText() + "8");//displays number 8
    }//GEN-LAST:event_numEightActionPerformed

    private void numNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numNineActionPerformed
        display.setText(display.getText() + "9");//displays number 9
    }//GEN-LAST:event_numNineActionPerformed

    private void numZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numZeroActionPerformed
        display.setText(display.getText() + "0");//displays number 0
    }//GEN-LAST:event_numZeroActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        
        //calls switch statement 2 to subtract numbers
        num = Double.parseDouble(display.getText());
        calculation = 2;
        display.setText("");
        label.setText(num + "-");
    }//GEN-LAST:event_minusButtonActionPerformed

    private void divButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divButtonActionPerformed
       
        //calls switch statement 4 to divide numbers
        num = Double.parseDouble(display.getText());
        calculation = 4;
        display.setText("");
        label.setText(num + "/");
    }//GEN-LAST:event_divButtonActionPerformed

    private void decimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalButtonActionPerformed
        display.setText(display.getText() + "."); //displays a decimal point
    }//GEN-LAST:event_decimalButtonActionPerformed

    private void offButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offButtonActionPerformed
        disable();  //call disable 
        
    }//GEN-LAST:event_offButtonActionPerformed

    private void equalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalButtonActionPerformed
       //calls aritmetic method 
        arithmetic();
       label.setText("");
    }//GEN-LAST:event_equalButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton decimalButton;
    private javax.swing.JTextField display;
    private javax.swing.JButton divButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JList<String> history;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton multButton;
    private javax.swing.JButton numEight;
    private javax.swing.JButton numFive;
    private javax.swing.JButton numFour;
    private javax.swing.JButton numNine;
    private javax.swing.JButton numOne;
    private javax.swing.JButton numSeven;
    private javax.swing.JButton numSix;
    private javax.swing.JButton numThree;
    private javax.swing.JButton numTwo;
    private javax.swing.JButton numZero;
    private javax.swing.JRadioButton offButton;
    private javax.swing.JRadioButton onButton;
    private javax.swing.JButton plusButton;
    // End of variables declaration//GEN-END:variables
}
